[package]
name = "pure_lang_compile_service_export"
version = "0.1.0"
edition = "2024"

[dependencies]
global = { package = "pure_lang_global", git = "https://github.com/ExPuritate/purelang_global.git" }
